version: '3.8'

services:
  database:
    container_name: tours-c-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=toursProject
    ports:
      - 3306:3306
    # image: sandwichproger/tours-db:1.0
    build: ./database 
    volumes:
      - tours-database:/var/lib/mysql
  backend:
    depends_on:
      - database
    container_name: tours-backend
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=compose
    build: ./backend
  frontend:
    depends_on:
      - backend
    container_name: tours-c-front
    ports:
      - 3000:80
    build: ./frontend

volumes:
  tours-database: